spring:
  application:
    name: etr-nfl
  config:
    import: optional:configserver:http://localhost:8888

server:
    port: 8181

logging:
  level:
    root: info
    com.establish.the.run: debug
    org.springframework.web.reactive: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 2s
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 5
      fail-after-max-attempts: true
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - io.netty.handler.timeout.TimeoutException
        - java.io.IOException
        - io.github.resilience4j.ratelimiter.RequestNotPermitted
        - java.lang.RuntimeException
  instances:
    sleeperService:
      baseConfig: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 15
        limit-refresh-period: 1s
    instances:
      sleeperService:
        baseConfig: default
